on:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup node
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: 'yarn'
    
    - name: Install dependencies
      shell: bash
      run: yarn install --frozen-lockfile
    
    - name: Run yarn test
      shell: bash
      run: yarn test